import "dotenv/config";
import fs from "fs";
import path from "path";
import { GoogleGenAI } from "@google/genai";

// --- CONFIGURATION ---
const INPUT_FILE = path.resolve("src/data.json");
const OUTPUT_FILE = path.resolve("src/analysis.json");
const ANALYST_MODEL = "gemini-3-flash-preview";

// Initialize Gemini
const ai = new GoogleGenAI({ apiKey: process.env.GOOGLEAI_API_KEY });

// --- 1. GROUPING LOGIC ---
const ModelNumberMap = {
  Gemini: 1,
  ChatGPT: 2,
  Claude: 3,
  Deepseek: 4,
};
function getGroupedPrompts(rawData) {
  const groups = {};

  rawData.forEach((item) => {
    // specific key to group by (using the prompt string itself)
    const key = item.prompt;

    if (!groups[key]) {
      groups[key] = {
        id: item.id, // Keep the ID of the first occurrence
        category: item.category,
        prompt: item.prompt,
        responses: {}, // Object to map Model Name -> Response Text
      };
    }

    // Add this model's response to the group
    groups[key].responses[ModelNumberMap[item.model]] = item.response;
  });

  return Object.values(groups);
}

// --- 2. ANALYSIS LOGIC ---

async function analyzeDifferences() {
  console.log("Reading data...");

  if (!fs.existsSync(INPUT_FILE)) {
    console.error("No data.json found!");
    return;
  }

  const rawData = JSON.parse(fs.readFileSync(INPUT_FILE, "utf-8"));
  const groupedData = getGroupedPrompts(rawData);

  console.log(`Found ${groupedData.length} unique prompts to analyze.`);

  // Load existing analysis if we want to resume logic (optional)
  let analyses = [];
  if (fs.existsSync(OUTPUT_FILE)) {
    try {
      analyses = JSON.parse(fs.readFileSync(OUTPUT_FILE, "utf-8"));
    } catch (e) {
      analyses = [];
    }
  }
  let i = 0;
  for (const group of groupedData) {
    i++;
    // if (i > 10) break; // TEMPORARY LIMIT FOR TESTING
    // Skip if we already analyzed this prompt ID
    console.log(`\n[${i}/${groupedData.length}]...`);
    if (analyses.find((a) => a.original_id === group.id)) {
      console.log(`[SKIP] ID ${group.id} already analyzed.`);
      continue;
    }

    // Only analyze if we have at least 2 models to compare
    const models = Object.keys(group.responses);
    if (models.length < 2) {
      console.log(`[SKIP] ID ${group.id}: Not enough models to compare.`);
      continue;
    }

    console.log(`\n--- Analyzing ID ${group.id} (${models.length} models) ---`);
    console.log(`Prompt: "${group.prompt}"`);
    // Construct the Meta-Prompt
    let metaPrompt = `
      You are an expert literary critic and AI behavior analyst. 
      I will provide a user prompt and the responses generated by several different AI models.
      
      Your goal is to identify the unique "fingerprint" of each model in this specific instance.

      USER PROMPT: "${group.prompt}"

      ---
    `;

    // Append each model's answer

    // we need to add modelIDs in a random order to avoid bias

    const modelIDs = Object.keys(group.responses);
    for (const modelID of modelIDs.sort(() => Math.random() - 0.5)) {
      const responseText = group.responses[modelID];
      metaPrompt += `\n[MODEL: ${modelID}]\n${responseText}\n---`;
    }

    metaPrompt += `
      \nTASK:
      Create a short, bulleted list for EACH model explaining strictly WHAT makes its response different from the others.
      Focus on: Tone, Structure, Conciseness, and Word Choice. Do not focus on what the text is about. Try to spot biases.
      
      Format the output cleanly in Markdown.
      Do not include a general intro, just start with the models. Type the model number and its bullets right after. Make 3 bullets for each model and keep them short.
    `;
    try {
      // Small delay to respect rate limits
      await new Promise((r) => setTimeout(r, 2000));

      const result = await ai.models.generateContent({
        model: ANALYST_MODEL,
        contents: metaPrompt,
      });

      const analysisText = result.text; // SDK compatibility

      // Save the result
      const analysisEntry = {
        original_id: group.id,
        analysis: analysisText, // The AI's comparison
      };

      analyses.push(analysisEntry);
      // Save immediately
      fs.writeFileSync(OUTPUT_FILE, JSON.stringify(analyses, null, 2));
      console.log("   -> Analysis saved.");
    } catch (error) {
      console.error("   -> Error analyzing:", error.message);
    }
  }

  console.log("\nDone! All analyses saved to analysis.json");
}

analyzeDifferences();
